### ISSUE TITLE
Reference code

### ISSUE THREAD

**Issue by ben-albrecht** [pgrew/mbb#1]
Check in some reference code for libSVM to reproduce with a Chapel interface.

### Reference Codes 

- [x] Classify the iris data set

**Comment by pgrew** [comment]
@ben-albrecht I've pushed branch `reference-python-classify-iris` with a working example classifier. Somehow, I never created a master branch...

**Comment by ben-albrecht** [comment]
> I've pushed branch reference-python-classify-iris with a working example classifier. 

Nice. I've added the Chapel svm wrappers to my [svm.chpl branch](https://github.com/ben-albrecht/mbb/commit/d0f526ac01f5c31caaeed200e0323fb5107434d2) -- I'll open an issue for the next step.

> Somehow, I never created a master branch...

huh, weird. Want to create a master branch for us to merge our branches into?

**Comment by pgrew** [comment]
I've merged my branch into master.
