### ISSUE TITLE
Understand all linear algebra required for PSVM

### ISSUE THREAD

**Issue by pgrew** [pgrew/mbb#5]
The PSVM paper, https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/34638.pdf, may use linear algebra operations or algorithms that are not currently implemented in Chapel. We should list every required operation and algorithm to compare with what Chapel supports now.

**Comment by pgrew** [comment]
@ben-albrecht We need matrix multiplication, matrix division, matrix addition, matrix inverses, the ["vec"](https://en.wikipedia.org/wiki/Vectorization_(mathematics)) transform, diagonal extraction, and scalar addition or subtraction from matrices.

**Comment by ben-albrecht** [comment]
*Check-listified*:

- [x] matrix multiplication
- [ ] matrix division
- [x] matrix addition
- [ ] matrix inverses
- [x] the ["vec"](https://en.wikipedia.org/wiki/Vectorization_(mathematics)) transform
- [x] diagonal extraction
- [x] scalar operations on matrices
- [x] trace

Division and inverses are coming with LAPACK support, and are straightforward to add.

Are these operations used to perform the incomplete Cholesky decomposition or will we need a routine for that too?

**Comment by pgrew** [comment]
Most of these are used in the parallel interior-point method. From what I can tell, the parallel incomplete Cholesky factorization doesn't use much linalg. Oh, add "trace" to your list :)
